### ISSUE TITLE
Make The User Aware Of How To Use Concurrency

### ISSUE THREAD

**Issue by samuel-esp** [caas-team/GoKubeDownscaler#111]
## Issue

Actually the default values for requests and limits for the Downscaler are set like this:

```yaml
resources:
  limits:
    cpu: 500m
    memory: 900Mi
  requests:
    cpu: 200m
    memory: 300Mi
```

Using a value of 500m in `resources.limits.cpu` will prevent the user from fully leveraging the concurrency in the code. An ideal value would be at least 2000m (in this way the user would take advantage of at least 2 full vCPUs if possible)

This is what happens for example for IstioProxy 

### Proposal

We could solve this "soft" problem in many possible ways

1) Make the user aware of this inside the docs
2) Set 2000m as the new default
3) Introducing a dedicated a variable in the Helm Chart that the user could leverage to specify its concurrency preference. If the variable is enabled the chart will check if `limit.cpu >= 2000m`, if not it will throw an error
